services:
  db:
    image: postgres:17.4-bookworm
    container_name: postgres
    env_file: ".env"
    ports:
      - ${POSTGRES_EXT_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build: .
    image: 'molecule-database-app'
    container_name: 'molecule-database-app'
    env_file: ".env"
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    driver: bridge