name: Build Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ env.IMAGE_NAME }}:latest